name: sage-diffusion
channels:
  - conda-forge
  - defaults
dependencies:
  - _r-mutex
  - alabaster
  - anyio
  - appnope
  - argon2-cffi
  - argon2-cffi-bindings
  - arpack
  - arrow
  - asttokens
  - async-lru
  - attrs
  - babel
  - bdw-gc
  - beautifulsoup4
  - beniget
  - blas-devel
  - bleach
  - bleach-with-css
  - brotli
  - brotli-bin
  - brotli-python
  - bwidget
  - bzip2
  - c-ares
  - ca-certificates
  - cached-property
  - cached_property
  - cairo
  - cctools_osx-arm64
  - cddlib
  - certifi
  - cffi
  - charset-normalizer
  - clang
  - clang-20
  - clang_impl_osx-arm64
  - clang_osx-arm64
  - clangxx
  - clangxx_impl_osx-arm64
  - clangxx_osx-arm64
  - cliquer
  - colorama
  - colorlog
  - comm
  - compiler-rt
  - compiler-rt_osx-arm64
  - contourpy
  - conway-polynomials
  - cpython
  - curl
  - cvxopt
  - cycler
  - cypari2
  - cysignals
  - cython
  - debugpy
  - decorator
  - defusedxml
  - docutils
  - dsdp
  - ecl
  - eclib
  - ecm
  - exceptiongroup
  - executing
  - fflas-ffpack
  - fftw
  - filelock
  - flintqs
  - font-ttf-dejavu-sans-mono
  - font-ttf-inconsolata
  - font-ttf-source-code-pro
  - font-ttf-ubuntu
  - fontconfig
  - fonts-conda-ecosystem
  - fonts-conda-forge
  - fonttools
  - fplll
  - fpylll
  - fqdn
  - freetype
  - fribidi
  - fsspec
  - future
  - gap-core
  - gap-defaults
  - gast
  - gettext
  - gettext-tools
  - gf2x
  - gfan
  - gfortran_impl_osx-arm64
  - gfortran_osx-arm64
  - giac
  - givaro
  - glpk
  - gmp
  - gmpy2
  - graphite2
  - gsl
  - h11
  - h2
  - harfbuzz
  - hpack
  - httpcore
  - httpx
  - hyperframe
  - icu
  - idna
  - igraph
  - imagesize
  - iml
  - importlib-metadata
  - importlib_resources
  - ipykernel
  - ipython
  - ipywidgets
  - isl
  - isoduration
  - jedi
  - jinja2
  - jmol
  - json5
  - jsonpointer
  - jsonschema
  - jsonschema-specifications
  - jsonschema-with-format-nongpl
  - jupyter-lsp
  - jupyter_client
  - jupyter_core
  - jupyter_events
  - jupyter_server
  - jupyter_server_terminals
  - jupyterlab
  - jupyterlab_pygments
  - jupyterlab_server
  - jupyterlab_widgets
  - kiwisolver
  - krb5
  - lcalc
  - lcms2
  - ld64_osx-arm64
  - lerc
  - libabseil
  - libamd
  - libasprintf
  - libasprintf-devel
  - libblas
  - libbraiding
  - libbrial
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libbtf
  - libcamd
  - libcblas
  - libccolamd
  - libcholmod
  - libclang-cpp20.1
  - libcolamd
  - libcurl
  - libcxsparse
  - libcxx
  - libcxx-devel
  - libdeflate
  - libedit
  - libev
  - libexpat
  - libffi
  - libflint
  - libfreetype
  - libfreetype6
  - libgd
  - libgettextpo
  - libgettextpo-devel
  - libgfortran
  - libgfortran-devel_osx-arm64
  - libgfortran5
  - libglib
  - libhomfly
  - libiconv
  - libintl
  - libintl-devel
  - libjpeg-turbo
  - libklu
  - liblapack
  - liblapacke
  - libldl
  - libllvm20
  - liblzma
  - libnghttp2
  - libopenblas
  - libparu
  - libpng
  - libprotobuf
  - librbio
  - libsodium
  - libspex
  - libspqr
  - libsqlite
  - libssh2
  - libsuitesparseconfig
  - libtiff
  - libtorch
  - libumfpack
  - libuv
  - libwebp-base
  - libxcb
  - libxml2
  - libzlib
  - linbox
  - llvm-openmp
  - llvm-tools
  - llvm-tools-20
  - lrcalc
  - m4ri
  - m4rie
  - make
  - markupsafe
  - matplotlib
  - matplotlib-base
  - matplotlib-inline
  - maxima
  - memory-allocator
  - metis
  - mistune
  - mpc
  - mpfi
  - mpfr
  - mpmath
  - munkres
  - nauty
  - nbclient
  - nbconvert
  - nbconvert-core
  - nbconvert-pandoc
  - nbformat
  - ncurses
  - nest-asyncio
  - networkx
  - nomkl
  - notebook
  - notebook-shim
  - ntl
  - numpy
  - openblas
  - openjdk
  - openjpeg
  - openssl
  - optree
  - overrides
  - packaging
  - palp
  - pandoc
  - pandocfilters
  - pango
  - pari
  - pari-galdata
  - pari-seadata-small
  - parso
  - pcre2
  - perl
  - pexpect
  - pickleshare
  - pillow
  - pip
  - pixman
  - pkg-config
  - pkgconfig
  - pkgutil-resolve-name
  - planarity
  - platformdirs
  - ply
  - ppl
  - pplpy
  - primecount
  - primecountpy
  - primesieve
  - prometheus_client
  - prompt-toolkit
  - psutil
  - pthread-stubs
  - ptyprocess
  - pure_eval
  - pybind11
  - pybind11-global
  - pycparser
  - pygments
  - pyobjc-core
  - pyobjc-framework-cocoa
  - pyparsing
  - pysocks
  - python
  - python-dateutil
  - python-fastjsonschema
  - python-json-logger
  - python-lrcalc
  - python_abi
  - pythran
  - pytorch
  - pytz
  - pyyaml
  - pyzmq
  - qd
  - qhull
  - r-base
  - readline
  - referencing
  - requests
  - rfc3339-validator
  - rfc3986-validator
  - roman-numerals-py
  - rpds-py
  - rpy2
  - rubiks
  - rw
  - sage
  - sagelib
  - sagemath-db-combinatorial-designs
  - sagemath-db-elliptic-curves
  - sagemath-db-graphs
  - sagemath-db-polytopes
  - sagetex
  - scikit-learn
  - scipy
  - send2trash
  - setuptools
  - sigtool
  - simplegeneric
  - singular
  - six
  - sleef
  - sniffio
  - snowballstemmer
  - soupsieve
  - sphinx
  - sphinxcontrib-applehelp
  - sphinxcontrib-devhelp
  - sphinxcontrib-htmlhelp
  - sphinxcontrib-jsmath
  - sphinxcontrib-qthelp
  - sphinxcontrib-serializinghtml
  - sqlite
  - stack_data
  - suitesparse
  - symmetrica
  - sympow
  - sympy
  - tachyon
  - tapi
  - terminado
  - threadpoolctl
  - three.js
  - threejs-sage
  - tinycss2
  - tk
  - tktable
  - tomli
  - tornado
  - traitlets
  - types-python-dateutil
  - typing-extensions
  - typing_extensions
  - typing_utils
  - tzdata
  - tzlocal
  - unicodedata2
  - uri-template
  - urllib3
  - wcwidth
  - webcolors
  - webencodings
  - websocket-client
  - wheel
  - widgetsnbextension
  - xorg-libxau
  - xorg-libxdmcp
  - yaml
  - zeromq
  - zipp
  - zlib
  - zn_poly
  - zstandard
  - zstd
  - pip:
      - einops
      - joblib
      - torchvision
      - tqdm
